---
title: Thomas Huet
# author: "Thomas Huet
# date: "11/12/2020"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}  #make every figure with capti
# output: 
#   html_document:
#     # template: my-template.html
#     template: null
output: html_document 
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE,  fig.align="center", fig.width = 12, fig.height = 12)
```

Labex ARCHIMEDE, Associate Researcher \n UMR 5140 ASM-CNRS \n Université Paul-Valéry Montpellier 3, France

* professional page: [https://archimede.cnrs.fr/index.php/annuaire/123-annuaire/e-h/456-thomas-huet](https://archimede.cnrs.fr/index.php/annuaire/123-annuaire/e-h/456-thomas-huet)
* mail: [thomashuet7@gmail.com](thomashuet7@gmail.com)
* [CV](https://github.com/zoometh/thomashuet.github.io/raw/main/cv/cv_english.pdf)

### Current researches

```{r Rshiny.apps}
shiny.apps.df <- data.frame(name=c("EUROEVOL_R",
                                "NeoNet",
                                "encounter_postdoc",
                                "Golasecca-net"),
                         topic=c("Radiocarbon mapping",
                                 "Radiocarbon mapping",
                                 "Radiocarbon mapping",
                                 "Networks & Open Science"),
                         web.url=c("https://zoometh.github.io/C14/",
                                   "https://zoometh.github.io/C14/neonet",
                             "https://zoometh.github.io/encounter_postdoc/docs/lf_jomon_sites.html",
                                   "https://zoometh.github.io/golasecca/"),
                         app.url=c("https://neolithic.shinyapps.io/Euroevol_R/",
                                   "https://neolithic.shinyapps.io/NeoNet/",
                                   "None",
                                   "None"))
kable(shiny.apps.df,"html") %>% 
  kable_styling(full_width = FALSE, position = "center", font_size=12)
```

