---
title: "Write functions in R"
author: "Thomas Huet, University of Oxford"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
```

## Functions in R: an overview

Native functions

```{r addition, exercise=TRUE}
sum(1, 1)
```

Help

```{r addition-h, exercise=TRUE}
?sum
```

## Exercices

### Parameters - typo

Fix the typo

```{r addition0, exercise=TRUE}
my_sum <- function(a, b){
  a + b
}

## here
my_sum(1, "1")
```

```{r addition0-solution}
my_sum(1, 1)
```

### Parameters - write

Write the missing parameters adding `1` and `2`

```{r addition1, exercise=TRUE}
my_sum <- function(a, b){
  a + b
}

## here
my_sum( , )
```

```{r addition1-solution}
my_sum(1, 2)
```

### Parameters - internal

Lorem

```{r varInter, exercise=TRUE}
my_loop <- function(a){
  for(i in a){
    print(i)
  }
}

## here
i <- "grey"
my_loop("red", "green", "blue", "orange")
print(i)
```


## Documentation

- https://tinystats.github.io/teacups-giraffes-and-statistics/01_introToR.html

## About this document

This document is a Rmarkdown file using the `learnr` package
